insightsengineering/cardx

DESCRIPTION, R/ard_proportion_ci.R
=> {cards} arg rename updates

R/ard_wilcoxtest.R, man/ard_wilcoxtest.Rd, tests/testthat/test-ard_wilcoxtest.R
* Updated `ard_wilcoxtest()` to allow multiple variables
closes #80 
=> Updated `ard_wilcoxtest()` to allow multiple variables

DESCRIPTION
=> Bumping broom.helpers required version to 1.15.0 (first version with official support for mmrm)

R/ard_regression.R, R/ard_regression_basic.R, R/construction_helpers.R, man/construction_helpers.Rd, tests/testthat/_snaps/construction_helpers.md, tests/testthat/test-ard_regression.R, tests/testthat/test-ard_regression_basic.R, tests/testthat/test-construction_helpers.R
* Removed all-NA `variable_level` column from regression ARDs constructed from simple linear regression models. (#134)
Also fixed failing example for `construct_model` which uses `ard_regression` but did not require `broom.helpers` to be installed.
Closes #134
=> Remove all-NA `variable_level` column from regression ARD output

R/ard_stats_oneway_test.R
=> Adding variable/group columns to `ard_stats_oneway_test()` results

R/ard_effectsize_cohens_d.R, R/ard_effectsize_hedges_g.R
=> Adding method to effectsize pkg ard functions

R/ard_continuous.survey.design.R
* Fix note occurring during installation
Closes #161 
=> Fix installation note

DESCRIPTION, R/construction_helpers.R
=> Check for simple calls in `construct_model()`

R/construction_helpers.R, tests/testthat/test-construction_helpers.R
=> updates to `.as_list_of_exprs()`

R/ard_categorical.survey.design.R, tests/testthat/_snaps/ard_categorical.survey.design.md, tests/testthat/test-ard_categorical.survey.design.R, tests/testthat/test-ard_continuous.survey.design.R
- found more protected names through testing 
- Added expect_equal tests to ensure other variables names work as expected
- Updated error messaging to include new variables
=> review protected names and add tests 

DESCRIPTION, man/cardx-package.Rd
* Added website URL to DESCRIPTION file.
Closes #188 
=> Add website URL to DESCRIPTION

DESCRIPTION, NEWS.md, R/construction_helpers.R, man/construction_helpers.Rd, tests/testthat/_snaps/construction_helpers.md, tests/testthat/test-construction_helpers.R
* The `bt(pattern)`, `reformulate2(pattern_term)`, `reformulate2(pattern_response)` arguments have been deprecated and are now ignored. We now use `make.names()` to determine whether a column name needs to be wrapped in backticks. (#192)
closes #192
=> `bt(pattern)` update

.github/workflows/scheduled.yaml, DESCRIPTION
set lme4 version to 1.1-35.3 to align with rspm
=> align lme4 version with current rspm version

R/ard_survival_survfit.R, man/ard_survival_survfit.Rd
=> adding example specifying conf level in `ard_survival_survfit()`

NEWS.md, R/ard_categorical.survey.design.R, R/ard_categorical_ci.R, tests/testthat/_snaps/ard_categorical.survey.design.md, tests/testthat/test-ard_categorical.survey.design.R
* Update in `ard_categorical.survey.design()` for factor variables that are all missing. These variables can now be tabulated, where previously this resulted in an error.
Addresses https://github.com/ddsjoberg/gtsummary/issues/2104
=> update for fct variables that are all NA

R/ard_categorical_ci.R, cardx.Rproj, man/ard_categorical_ci.Rd, tests/testthat/test-ard_categorical_ci.data.frame.R
* Adding `ard_categorical_ci.data.frame(denominator)` argument, which can change the direction or denominator of the confidence interval calculation. It's similar to the `cards::ard_categorical.data.frame(denominator)` argument. (#204)
closes #204
=> Adding `ard_categorical_ci(denominator)` argument

DESCRIPTION, NEWS.md, R/ard_categorical.survey.design.R, R/ard_categorical_ci.R, tests/testthat/test-ard_categorical_ci.data.frame.R
* Added `as_cards_fun()` to `ard_categorical_ci()` so when there is an error, the user gets an ARD with the expected ARD structure. (#262)
closes #262
=> Adding `as_cards_fun()` to `ard_categorical_ci()`

NEWS.md, R/ard_categorical_ci.R, R/proportion_ci.R, man/ard_categorical_ci.Rd, man/ard_categorical_ci.survey.design.Rd, man/dot-strata_normal_quantile.Rd, man/dot-update_weights_strat_wilson.Rd, man/proportion_ci.Rd, tests/testthat/test-ard_categorical_ci.data.frame.R
* Bug fix in `ard_categorical_ci(denominator='cell')` when missing values were present in the `by` variable.
=> better handling of NA values in `ard_categorical_ci()`

DESCRIPTION
=> Increase cards min version req

R/ard_survival_survfit.R, tests/testthat/_snaps/ard_survival_survfit.md, tests/testthat/test-ard_survival_survfit.R
* Added checks to `ard_survival_survfit()` to check for missing parameters.
Closes #275 
=> Add parameter checks to `ard_survival_survfit()`

R/import-standalone-forcats.R
closes #296 
Introduce this check: https://github.com/insightsengineering/standalone/pull/16
=> update forcats standalone script
